name: Deploy Docker Compose to EC2

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. SSH 키 설정
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # 3. EC2 서버로 Docker Compose 파일 전송
      - name: Transfer Docker Compose file to EC2
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/docker-compose.yml

      # 4. EC2 서버에서 Docker Compose 실행
      - name: Run Docker Compose on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          docker-compose -f /home/ec2-user/docker-compose.yml pull
          docker-compose -f /home/ec2-user/docker-compose.yml up -d
          EOF
